#!/usr/bin/env sh

/usr/local/bin/limelight -m config width 2
/usr/local/bin/limelight -m config radius 10
/usr/local/bin/limelight -m config placement exterior
/usr/local/bin/limelight -m config active_color 0x8898971A
/usr/local/bin/limelight -m config normal_color 0x00504945

echo "limelight configuration loaded.."
